# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "commander", "~>4.0"
gem "hpricot", "~>0.0"

gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>3.5", :group => [:development, :test]

# vim: syntax=ruby
